### PR TITLE
centered images and title

### LINKED ISSUE #3: Center the POKEDEX heading and searchbar
image
There is a lot of space to the left of the searchbar and heading, this needs to be resolved by centering these two items horizontally.

### LINKED ISSUE #6: Add box-shadow to the pokemon blocks
Adding box-shadows to the cards would make them look like having depth, hence box-shadows need to be added to them.

### LINKED ISSUE #7: Center image and title of pokemon cards
image
Currently the title and image are not on top of one other, instead are to the left and right of each other, this needs to be fixed.

### LINKED ISSUE #8: Stack pokemon horizontally instead of vertically
image
Currently the pokemon cards are stacked on top of each other, it would be better if they are placed next to each other horizontally row-wise.

### LINKED ISSUE #9: Ensure responsiveness of the page
The page needs to be made responsive for smaller screen devices.

### LINKED ISSUE #11: Round the pokemon card borders
Rounding the edges of the cards a bit would make them look better once boxshadow and border are implemented.

### PR DESCRIPTION
**Pull request by ImAnshuJoshi**
image
I have centered all the things .

closes #3 
closes #11 
closes #6 
closes #7 
closes #8 
closes #9

### CODE REVIEW

**Comment by XDRAGON2002** [comment]
@ImAnshuJoshi Well, since you've combined together a lot of issues in a single PR, go ahead and add all those issues as `Closes #issue1` `Closes #issue2` in your PR description, also a reminder for next time, try to keep the PRs atomic, i.e. each PR must only resolve a single issue.
Other than that great work! Link the issues and I'll merge this!

**Comment by ImAnshuJoshi** [comment]
@XDRAGON2002 , done.

**Comment by XDRAGON2002** [comment]
Replace #4 with #11.

**Comment by ImAnshuJoshi** [comment]
@XDRAGON2002 , I have updated that .

**Comment by XDRAGON2002** [comment]
LGTM!

**Pull request merged**
